#! /bin/sh

case $1 in
    start)
        [ -r /oem/RkLunch.sh ] && sh /oem/RkLunch.sh
        ;;
    stop)
        [ -r /oem/RkLunch-stop.sh ] && sh /oem/RkLunch-stop.sh
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        ;;
esac
