#! /bin/sh

[ -f /usr/bin/input-event-daemon ] || exit 0

start() {
	input-event-daemon
}


stop() {
	killall input-event-daemon 2>/dev/null || true
}

restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|reload|restart}"
	exit 1
esac

exit $?
